"""Initial tables for VOICEcheck

Revision ID: 001_initial_tables
Revises:
Create Date: 2025-02-16 23:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid


# revision identifiers, used by Alembic.
revision = '001_initial_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table('dialogs',
    sa.Column('id', UUID(as_uuid=True), nullable=False, primary_key=True, default=uuid.uuid4),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, default='pending'),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogs_created_at'), 'dialogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dialogs_filename'), 'dialogs', ['filename'], unique=False)
    op.create_index(op.f('ix_dialogs_id'), 'dialogs', ['id'], unique=False)
    op.create_index(op.f('ix_dialogs_status'), 'dialogs', ['status'], unique=False)
    op.create_index(op.f('ix_dialogs_updated_at'), 'dialogs', ['updated_at'], unique=False)

    op.create_table('transcriptions',
    sa.Column('id', UUID(as_uuid=True), nullable=False, primary_key=True, default=uuid.uuid4),
    sa.Column('dialog_id', UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('language_probability', sa.Float(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_dialog_id'), 'transcriptions', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)

    op.create_table('dialog_analyses',
    sa.Column('id', UUID(as_uuid=True), nullable=False, primary_key=True, default=uuid.uuid4),
    sa.Column('dialog_id', UUID(as_uuid=True), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('key_moments', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('speaking_time', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dialog_id')
    )
    op.create_index(op.f('ix_dialog_analyses_dialog_id'), 'dialog_analyses', ['dialog_id'], unique=True)
    op.create_index(op.f('ix_dialog_analyses_id'), 'dialog_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialog_analyses_id'), table_name='dialog_analyses')
    op.drop_index(op.f('ix_dialog_analyses_dialog_id'), table_name='dialog_analyses')
    op.drop_table('dialog_analyses')
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_dialog_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_dialogs_updated_at'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_status'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_id'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_filename'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_created_at'), table_name='dialogs')
    op.drop_table('dialogs')
    # ### end Alembic commands ###